### ISSUE TITLE
Unresolved external symbol on Windows

### ISSUE THREAD

**Issue by chansen** [Leont/perlio-utf8_strict#2]
`PerlIOBase_flush_linebuf` is unresolved on Windows, "error LNK2019: unresolved external symbol _PerlIOBase_flush_linebuf referenced in function _PerlIOUnicode_fill".

Failing Windows reports: http://www.cpantesters.org/distro/P/PerlIO-utf8_strict.html#PerlIO-utf8_strict-0.002?grade=3
## 

chansen

**Comment by Leont** [comment]
This was fixed in 0.004
